'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { ContactActions } from '@/components/command/ContactActions';
import { commandApi } from '@/lib/command/api';

const tabs = ['Timeline', 'Opportunities', 'Smart Plans', 'Tasks', 'Bookings', 'Notes', 'Saved Searches'] as const;
export default function Page() {
  const { contactId } = useParams<{ contactId: string }>(); const [data, setData] = useState<any>(null); const [tab, setTab] = useState<typeof tabs[number]>('Timeline'); const [error, setError] = useState('');
  useEffect(() => { void commandApi.contactWorkspace(Number(contactId)).then(setData).catch((err) => setError(err.message)); }, [contactId]);
  async function updateStage(stage: string) { try { const contact = await commandApi.updateContactStage(Number(contactId), stage); setData((current: any) => ({ ...current, contact })); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update stage'); } }
  async function editProfile() { if (!data) return; const first_name = window.prompt('First name', data.contact.first_name); if (first_name === null || !first_name.trim()) return; const last_name = window.prompt('Last name', data.contact.last_name); if (last_name === null) return; const email = window.prompt('Email', data.contact.email ?? ''); if (email === null) return; const phone = window.prompt('Phone', data.contact.phone ?? ''); if (phone === null) return; const birthday = window.prompt('Birthday (YYYY-MM-DD, blank to clear)', data.contact.birthday ?? ''); if (birthday === null) return; const anniversary = window.prompt('Anniversary (YYYY-MM-DD, blank to clear)', data.contact.anniversary ?? ''); if (anniversary === null) return; try { const contact = await commandApi.updateContact(Number(contactId), { first_name: first_name.trim(), last_name, email: email || null, phone: phone || null, birthday: birthday || null, anniversary: anniversary || null }); setData((current: any) => ({ ...current, contact })); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update profile'); } }
  if (!data) return <div className="min-h-[100dvh] bg-[#080807] p-8 text-white">Loading contact workspace…</div>;
  const map: any = { Timeline: data.timeline, Opportunities: data.opportunities, 'Smart Plans': data.smart_plans, Tasks: data.tasks, Bookings: data.bookings, Notes: data.notes, 'Saved Searches': data.saved_searches };
  return <div className="min-h-[100dvh] bg-[#080807] p-6 text-white"><main className="mx-auto max-w-5xl"><p className="text-xs uppercase tracking-[.25em] text-[#eac469]">Contact workspace</p><div className="mt-1 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black">{data.contact.first_name} {data.contact.last_name}</h1><button onClick={editProfile} className="rounded-lg border border-white/15 px-3 py-2 text-xs text-white/70 hover:border-[#eac469]">Edit profile</button></div>{error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}<div className="mt-3 flex flex-wrap gap-2">{data.contact.birthday && <span className="rounded-full border border-[#eac469]/30 px-2 py-1 text-xs text-[#eac469]">Birthday · {data.contact.birthday}</span>}{data.contact.anniversary && <span className="rounded-full border border-[#eac469]/30 px-2 py-1 text-xs text-[#eac469]">Anniversary · {data.contact.anniversary}</span>}{data.tags?.map((tag: any) => <span key={tag.id} className="rounded-full bg-[#eac469]/15 px-2 py-1 text-xs text-[#eac469]">{tag.name}</span>)}</div><label className="mt-3 block max-w-xs text-xs uppercase tracking-widest text-white/45">Stage<select value={data.contact.stage} onChange={(event) => updateStage(event.target.value)} className="mt-2 block w-full rounded-lg border border-white/10 bg-black/40 p-2 text-sm normal-case tracking-normal text-white">{['lead', 'nurture', 'appointment', 'client', 'past_client', 'lost'].map((stage) => <option key={stage} value={stage}>{stage.replace('_', ' ')}</option>)}</select></label><ContactActions contactId={contactId} /><div className="mt-7 flex gap-2 overflow-auto">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${tab === item ? 'bg-[#eac469] text-black' : 'bg-white/5 text-white/60'}`}>{item}</button>)}</div><section className="mt-5 rounded-2xl border border-white/10 bg-white/[.035] p-5">{map[tab].length ? map[tab].map((item: any) => <article key={item.id} className="border-b border-white/10 py-4 last:border-0"><b>{item.summary ?? item.title ?? item.name ?? item.meeting_type ?? `Plan #${item.plan_id}`}</b><p className="mt-1 text-sm text-white/45">{item.body ?? item.kind ?? item.status ?? item.stage ?? item.context ?? ''}</p>{item.scheduled_at && <p className="mt-1 text-xs text-[#eac469]">{new Date(item.scheduled_at).toLocaleString()}</p>}{item.criteria && <pre className="mt-2 overflow-auto rounded bg-black/30 p-2 text-xs text-white/50">{typeof item.criteria === 'string' ? item.criteria : JSON.stringify(item.criteria, null, 2)}</pre>}</article>) : <p className="py-10 text-center text-white/40">No {tab.toLowerCase()} for this contact.</p>}</section></main></div>;
}
