'use client';
import { useEffect, useMemo, useState } from 'react';
import { Plus, Users, WarningCircle } from '@phosphor-icons/react';
import { commandApi, type Contact } from '@/lib/command/api';

export function ContactsWorkspace(){
  const [items,setItems]=useState<Contact[]>([]),[query,setQuery]=useState(''),[error,setError]=useState<string|null>(null),[open,setOpen]=useState(false);
  const [draft,setDraft]=useState({first_name:'',last_name:'',email:'',phone:''});
  const load=()=>commandApi.contacts().then(setItems).catch(e=>setError(e.message)); useEffect(()=>{ void load(); },[]);
  const filtered=useMemo(()=>items.filter(c=>`${c.first_name} ${c.last_name} ${c.email??''}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  async function add(){try{const created=await commandApi.createContact(draft);setItems(x=>[created,...x]);setOpen(false);setDraft({first_name:'',last_name:'',email:'',phone:''})}catch(e){setError(e instanceof Error?e.message:'Unable to create contact')}}
  return <div className="min-h-[100dvh] bg-[#080807] p-6 text-white"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-[#eac469]">Internal CRM</p><h1 className="mt-1 text-3xl font-black">Contacts</h1></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#eac469] px-4 py-2 font-bold text-black"><Plus size={17}/>Add contact</button></header><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search contacts" className="mt-6 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 outline-none focus:border-[#eac469]"/>{error&&<p className="mt-4 flex gap-2 text-red-300"><WarningCircle size={18}/>{error}</p>}<div className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-white/[.035]"><table className="w-full text-left text-sm"><thead className="bg-white/5 text-xs uppercase tracking-widest text-white/45"><tr><th className="p-4">Contact</th><th className="p-4">Email</th><th className="p-4">Phone</th><th className="p-4">Stage</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id} className="border-t border-white/10"><td className="p-4 font-semibold">{c.first_name} {c.last_name}</td><td className="p-4 text-white/60">{c.email??'—'}</td><td className="p-4 text-white/60">{c.phone??'—'}</td><td className="p-4"><span className="rounded-full bg-[#eac469]/15 px-2 py-1 text-xs text-[#eac469]">{c.stage}</span></td></tr>)}{!filtered.length&&<tr><td className="p-12 text-center text-white/40" colSpan={4}><Users size={28} className="mx-auto mb-3"/>No contacts found</td></tr>}</tbody></table></div>{open&&<div className="fixed inset-0 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#12110f] p-6"><h2 className="text-xl font-bold">New contact</h2>{(['first_name','last_name','email','phone'] as const).map(k=><input key={k} value={draft[k]} placeholder={k.replace('_',' ')} onChange={e=>setDraft({...draft,[k]:e.target.value})} className="mt-3 w-full rounded-lg border border-white/10 bg-black/30 p-3 capitalize"/>)}<div className="mt-5 flex justify-end gap-3"><button onClick={()=>setOpen(false)} className="text-white/60">Cancel</button><button onClick={add} disabled={!draft.first_name} className="rounded-lg bg-[#eac469] px-4 py-2 font-bold text-black disabled:opacity-40">Save</button></div></div></div>}</div></div>
}
