"""add hero image columns to funnels

Revision ID: 9c1fb48ea689
Revises: 8fa950e372a8
Create Date: 2026-03-23 01:44:22.626006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1fb48ea689'
down_revision: Union[str, None] = '8fa950e372a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funnels', sa.Column('hero_image_url', sa.String(length=500), nullable=True))
    op.add_column('funnels', sa.Column('hero_image_data', sa.LargeBinary(), nullable=True))
    op.add_column('funnels', sa.Column('hero_image_mime', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funnels', 'hero_image_mime')
    op.drop_column('funnels', 'hero_image_data')
    op.drop_column('funnels', 'hero_image_url')
    # ### end Alembic commands ###
