'use client';

import { useEffect, useState } from 'react';
import { ChartBar } from '@phosphor-icons/react';
import { commandApi, type ReportDetails } from '@/lib/command/api';

export default function Page() {
  const [summary, setSummary] = useState<Record<string, number> | null>(null); const [events, setEvents] = useState<{ event_type: string; count: number }[]>([]); const [detail, setDetail] = useState<ReportDetails | null>(null); const [error, setError] = useState('');
  useEffect(() => { void commandApi.reportsSummary().then(setSummary).catch((err) => setError(err.message)); void commandApi.eventBreakdown().then(({ events: rows }) => setEvents(rows)).catch((err) => setError(err.message)); }, []);
  async function openDetail(metric: string) { try { setDetail(await commandApi.reportDetails(metric)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load report detail'); } }
  return <div className="min-h-[100dvh] bg-[#080807] p-6 text-white"><main className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-[.25em] text-[#eac469]">Internal reporting</p><h1 className="mt-1 text-3xl font-black">Reports</h1>{error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{summary ? Object.entries(summary).map(([label, value]) => <button onClick={() => openDetail(label)} key={label} className="rounded-2xl border border-white/10 bg-white/[.035] p-5 text-left transition hover:border-[#eac469]/50"><ChartBar className="text-[#eac469]" size={21} /><p className="mt-7 text-3xl font-black">{value.toLocaleString()}</p><p className="mt-1 text-xs uppercase tracking-widest text-white/45">{label.replace('_', ' ')} · View details</p></button>) : Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-36 animate-pulse rounded-2xl bg-white/5" />)}</div>{detail && <section className="mt-7 rounded-2xl border border-[#eac469]/30 bg-[#eac469]/[.04] p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{detail.metric.replace('_', ' ')} details</h2><button onClick={() => setDetail(null)} className="text-xs text-white/55">Close</button></div>{detail.rows.length ? <div className="mt-4 divide-y divide-white/10">{detail.rows.map((row) => <article key={row.id} className="py-3"><b className="text-sm">{row.title}</b><p className="mt-1 text-xs text-white/50">{row.detail}{row.occurred_at ? ` · ${new Date(row.occurred_at).toLocaleString()}` : ''}</p></article>)}</div> : <p className="mt-3 text-sm text-white/45">No records in this metric yet.</p>}</section>}<section className="mt-7 rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-bold">Event breakdown</h2>{events.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{events.map((event) => <p key={event.event_type} className="rounded-lg bg-black/25 p-3 text-sm text-white/65"><b className="text-white">{event.count.toLocaleString()}</b> · {event.event_type}</p>)}</div> : <p className="mt-3 text-sm text-white/40">No analytics event records yet.</p>}</section></main></div>;
}
