'use client';

import { useEffect, useState } from 'react';
import { ChartBar } from '@phosphor-icons/react';
import { commandApi } from '@/lib/command/api';

export default function Page() {
  const [summary, setSummary] = useState<Record<string, number> | null>(null); const [events, setEvents] = useState<{ event_type: string; count: number }[]>([]); const [error, setError] = useState('');
  useEffect(() => { const token = localStorage.getItem('admin_token'); const base = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000'; void fetch(`${base}/api/v1/command/reports/summary`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.json()).then(setSummary).catch((err) => setError(err.message)); void commandApi.eventBreakdown().then(({ events: rows }) => setEvents(rows)).catch((err) => setError(err.message)); }, []);
  return <div className="min-h-[100dvh] bg-[#080807] p-6 text-white"><main className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-[.25em] text-[#eac469]">Internal reporting</p><h1 className="mt-1 text-3xl font-black">Reports</h1>{error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{summary ? Object.entries(summary).map(([label, value]) => <section key={label} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><ChartBar className="text-[#eac469]" size={21} /><p className="mt-7 text-3xl font-black">{value.toLocaleString()}</p><p className="mt-1 text-xs uppercase tracking-widest text-white/45">{label.replace('_', ' ')}</p></section>) : Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-36 animate-pulse rounded-2xl bg-white/5" />)}</div><section className="mt-7 rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-bold">Event breakdown</h2>{events.length ? <div className="mt-4 grid gap-2 sm:grid-cols-2">{events.map((event) => <p key={event.event_type} className="rounded-lg bg-black/25 p-3 text-sm text-white/65"><b className="text-white">{event.count.toLocaleString()}</b> · {event.event_type}</p>)}</div> : <p className="mt-3 text-sm text-white/40">No analytics event records yet.</p>}</section></main></div>;
}
