'use client';

import { useEffect, useMemo, useState } from 'react';
import { MapPin, Plus } from '@phosphor-icons/react';
import { commandApi, type Listing } from '@/lib/command/api';

export default function Page() {
  const [items, setItems] = useState<Listing[]>([]); const [address, setAddress] = useState(''); const [selected, setSelected] = useState<number | null>(null); const [error, setError] = useState('');
  useEffect(() => { void commandApi.listings().then(setItems).catch((err) => setError(err.message)); }, []);
  const mapped = useMemo(() => items.map((item) => ({ item, lat: Number(item.latitude), lng: Number(item.longitude) })).filter(({ lat, lng }) => Number.isFinite(lat) && Number.isFinite(lng)), [items]);
  const bounds = useMemo(() => ({ minLat: Math.min(...mapped.map((item) => item.lat), 0), maxLat: Math.max(...mapped.map((item) => item.lat), 1), minLng: Math.min(...mapped.map((item) => item.lng), 0), maxLng: Math.max(...mapped.map((item) => item.lng), 1) }), [mapped]);
  async function add() { if (!address.trim()) return; try { const item = await commandApi.createListing({ address: address.trim(), latitude: null, longitude: null }); setItems((all) => [item, ...all]); setAddress(''); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to add listing'); } }
  async function geocode(id: number) { try { const updated = await commandApi.geocodeListing(id); setItems((all) => all.map((item) => item.id === id ? updated : item)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to geocode listing'); } }
  return <div className="min-h-[100dvh] bg-[#080807] p-6 text-white"><main className="mx-auto max-w-5xl"><p className="text-xs uppercase tracking-[.25em] text-[#eac469]">Internal inventory</p><h1 className="mt-1 text-3xl font-black">Listings & Map</h1><div className="mt-6 flex gap-3"><input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Add listing address" className="flex-1 rounded-xl border border-white/10 bg-white/5 p-3" /><button onClick={add} className="rounded-xl bg-[#eac469] px-4 text-black"><Plus /></button></div>{error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}<div className="mt-6 grid gap-4 lg:grid-cols-[1fr_.8fr]"><div className="space-y-2">{items.map((item) => <div key={item.id} className={`rounded-xl border p-4 ${selected === item.id ? 'border-[#eac469] bg-[#eac469]/10' : 'border-white/10 bg-white/[.035]'}`}><button onClick={() => setSelected(item.id)} className="w-full text-left"><b>{item.address}</b><p className="mt-1 text-xs text-white/40">{item.status} {item.latitude ? `· ${item.latitude}, ${item.longitude}` : '· Awaiting geocode'}</p></button>{!item.latitude && <button onClick={() => geocode(item.id)} className="mt-3 text-xs font-bold text-[#eac469]">Geocode address</button>}</div>)}</div><div className="relative min-h-64 overflow-hidden rounded-2xl border border-[#eac469]/30 bg-[linear-gradient(135deg,#17130a,#080807)]">{mapped.map(({ item, lat, lng }) => { const x = bounds.maxLng === bounds.minLng ? 50 : 10 + ((lng - bounds.minLng) / (bounds.maxLng - bounds.minLng)) * 80; const y = bounds.maxLat === bounds.minLat ? 50 : 10 + ((bounds.maxLat - lat) / (bounds.maxLat - bounds.minLat)) * 80; return <button title={item.address} onClick={() => setSelected(item.id)} key={item.id} style={{ left: `${x}%`, top: `${y}%` }} className={`absolute grid h-9 w-9 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full ${selected === item.id ? 'bg-white text-black' : 'bg-[#eac469] text-black'}`}><MapPin weight="fill" /></button>; })}{!mapped.length && <div className="grid h-full min-h-64 place-items-center text-center text-white/45"><div><MapPin className="mx-auto text-[#eac469]" size={32} /><p className="mt-3">Geocode a listing address to place it geographically on this internal map.</p></div></div>}</div></div></main></div>;
}
