'use client';

import { useEffect, useState } from 'react';
import type { ComponentType } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ChartBar, CheckCircle, ClipboardText, FileText, House, MapPin, Megaphone, Users, WarningCircle, Sparkle } from '@phosphor-icons/react';
import { commandApi, type Celebrations, type Contact, type Goal, type Overview, type Task } from '@/lib/command/api';

const nav = [
  ['Contacts', '/admin/command/contacts', Users], ['Tasks', '/admin/command/tasks', CheckCircle], ['Smart Plans', '/admin/command/smart-plans', Sparkle], ['Opportunities', '/admin/command/opportunities', ChartBar], ['Marketing', '/admin/command/marketing', Megaphone], ['Agreements', '/admin/command/agreements', FileText], ['Reports', '/admin/command/reports', ClipboardText], ['Listings & Map', '/admin/command/listings', MapPin], ['Websites', '/admin/command/websites', House],
] as const;

export default function CommandPage() {
  const [overview, setOverview] = useState<Overview | null>(null);
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [celebrations, setCelebrations] = useState<Celebrations | null>(null);
  const [goals, setGoals] = useState<Goal[]>([]); const [goalName, setGoalName] = useState(''); const [goalTarget, setGoalTarget] = useState(''); const [goalPeriod, setGoalPeriod] = useState<Goal['period']>('monthly');
  const [section, setSection] = useState('Command Home');
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([commandApi.overview(), commandApi.contacts(), commandApi.tasks(), commandApi.celebrations(new Date().getMonth() + 1), commandApi.goals()]).then(([o,c,t,celebrationData,goalRows]) => { setOverview(o); setContacts(c); setTasks(t); setCelebrations(celebrationData); setGoals(goalRows); }).catch(e => setError(e.message)); }, []);
  const metrics: [string, number, ComponentType<{ size?: number; className?: string }>][] = overview ? [['Contacts', overview.contacts, Users], ['Open Tasks', overview.open_tasks, CheckCircle], ['Opportunities', overview.opportunities, ChartBar], ['Active Smart Plans', overview.active_smart_plans, Sparkle]] : [];
  async function addGoal() { const target = Number(goalTarget); if (!goalName.trim() || !Number.isInteger(target) || target < 1) return; try { const goal = await commandApi.createGoal({ name: goalName.trim(), target_value: target, current_value: 0, period: goalPeriod }); setGoals((all) => [goal, ...all]); setGoalName(''); setGoalTarget(''); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create goal'); } }
  async function updateGoal(goal: Goal) { const value = window.prompt(`Current progress for ${goal.name}`, String(goal.current_value)); if (value === null || !Number.isInteger(Number(value)) || Number(value) < 0) return; try { const updated = await commandApi.updateGoalProgress(goal.id, Number(value)); setGoals((all) => all.map((item) => item.id === updated.id ? updated : item)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to update goal'); } }
  return <div className="min-h-[100dvh] bg-[#080807] text-white p-5 lg:p-8">
    <div className="mx-auto max-w-[1500px] grid gap-5 lg:grid-cols-[210px_1fr]">
      <aside className="rounded-2xl border border-white/10 bg-white/[0.035] p-3 h-fit lg:sticky lg:top-6">
        <p className="px-3 py-3 text-[10px] uppercase tracking-[.26em] text-[#eac469]">Sold With Sweeney</p>
        <button onClick={() => setSection('Command Home')} className={`w-full rounded-xl px-3 py-3 text-left text-sm ${section === 'Command Home' ? 'bg-[#eac469] text-black font-bold' : 'text-white/60 hover:bg-white/5'}`}>Command Home</button>
        {nav.map(([label, href, Icon]) => <Link key={label} href={href} className={`mt-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm ${section === label ? 'bg-white/10 text-white' : 'text-white/60 hover:bg-white/5'}`}><Icon size={17}/>{label}</Link>)}
      </aside>
      <main className="min-w-0">
        <header className="mb-6 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-[#eac469]">Internal CRM workspace</p><h1 className="mt-1 text-3xl font-black">{section}</h1></div><a href="/admin/command/ai" className="rounded-xl border border-[#eac469]/40 px-4 py-2 text-sm text-[#eac469]">Ask Sweeney AI</a></header>
        {error ? <div className="flex gap-3 rounded-2xl border border-red-400/30 bg-red-500/10 p-5 text-red-200"><WarningCircle size={22}/><p>{error}</p></div> : !overview ? <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[1,2,3,4].map(i => <div key={i} className="h-32 animate-pulse rounded-2xl bg-white/5"/>)}</div> : <>
          <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon], i) => <motion.div key={String(label)} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{type:'spring',stiffness:100,damping:20,delay:i*.05}} className="rounded-2xl border border-white/10 bg-gradient-to-br from-white/[.08] to-transparent p-5"><Icon className="text-[#eac469]" size={22}/><p className="mt-6 text-3xl font-black">{value}</p><p className="mt-1 text-xs uppercase tracking-widest text-white/45">{label}</p></motion.div>)}</section>
          <section className="mt-6 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-bold">Priority tasks</h2><div className="mt-4 divide-y divide-white/10">{tasks.slice(0,6).map(task => <div key={task.id} className="flex items-center justify-between py-3"><div><p className="text-sm font-medium">{task.title}</p><p className="text-xs text-white/40">{task.priority} priority {task.due_at ? `· due ${new Date(task.due_at).toLocaleDateString()}` : ''}</p></div><span className="rounded-full bg-[#eac469]/15 px-2 py-1 text-[10px] uppercase text-[#eac469]">{task.status}</span></div>)}{tasks.length===0 && <p className="py-8 text-sm text-white/40">No tasks yet. Tasks created here are persisted in the internal CRM.</p>}</div></div>
          <div className="space-y-5"><div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-bold">Recent contacts</h2><div className="mt-4 space-y-3">{contacts.slice(0,5).map(c => <div key={c.id} className="rounded-xl bg-black/20 p-3"><p className="text-sm font-medium">{c.first_name} {c.last_name}</p><p className="mt-1 text-xs text-white/40">{c.email ?? c.phone ?? 'No contact method'}</p></div>)}{contacts.length===0 && <p className="py-8 text-sm text-white/40">Contacts will appear here as they are added or linked from leads.</p>}</div></div><div className="rounded-2xl border border-[#eac469]/20 bg-[#eac469]/[.045] p-5"><h2 className="font-bold">This month’s celebrations</h2><div className="mt-3 space-y-2 text-sm">{celebrations && [...celebrations.birthdays.map(contact => ({contact, label: 'Birthday', date: contact.birthday})), ...celebrations.anniversaries.map(contact => ({contact, label: 'Anniversary', date: contact.anniversary}))].slice(0,5).map(({contact, label, date}) => <div key={`${label}-${contact.id}`} className="flex justify-between rounded-lg bg-black/20 px-3 py-2"><span>{contact.first_name} {contact.last_name}</span><span className="text-xs text-[#eac469]">{label}{date ? ` · ${new Date(`${date}T00:00:00`).toLocaleDateString(undefined, {month:'short', day:'numeric'})}` : ''}</span></div>)}{celebrations && celebrations.birthdays.length + celebrations.anniversaries.length === 0 && <p className="py-3 text-sm text-white/45">No private birthday or anniversary records this month.</p>}{!celebrations && <div className="h-10 animate-pulse rounded bg-white/5"/>}</div></div></div></section>
          <section className="mt-6 rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">Goals</h2><div className="flex flex-wrap gap-2"><input value={goalName} onChange={(event) => setGoalName(event.target.value)} placeholder="Goal name" className="w-36 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/><input value={goalTarget} onChange={(event) => setGoalTarget(event.target.value)} inputMode="numeric" placeholder="Target" className="w-20 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/><select aria-label="Goal period" value={goalPeriod} onChange={(event) => setGoalPeriod(event.target.value as Goal['period'])} className="rounded-lg border border-white/10 bg-black/30 px-2 py-2 text-xs">{(['weekly','monthly','quarterly','annual'] as const).map(period => <option key={period} value={period}>{period}</option>)}</select><button onClick={addGoal} className="rounded-lg bg-[#eac469] px-3 py-2 text-xs font-bold text-black">Add goal</button></div></div>{goals.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{goals.map(goal => { const percentage = Math.min(100, Math.round((goal.current_value / goal.target_value) * 100)); return <button onClick={() => updateGoal(goal)} key={goal.id} className="rounded-xl bg-black/20 p-4 text-left transition hover:bg-black/35"><div className="flex justify-between gap-3"><span className="font-medium">{goal.name}</span><span className="text-xs text-[#eac469]">{goal.current_value}/{goal.target_value}</span></div><div className="mt-3 h-1.5 overflow-hidden rounded bg-white/10"><div className="h-full rounded bg-[#eac469]" style={{width:`${percentage}%`}}/></div><p className="mt-2 text-xs uppercase tracking-widest text-white/40">{goal.period} · {percentage}% · Update progress</p></button>})}</div> : <p className="mt-3 text-sm text-white/45">No goals set yet.</p>}</section>
        </>}
      </main>
    </div>
  </div>;
}
